ASSUME CS:CODE, DS:DATA

DATA SEGMENT 
    MSG1 DB 0AH,0DH,"ENTER STRING:$"
    MSG2 DB 0AH,0DH,"PALINDROME$"
    MSG3 DB 0AH,0DH,"NOT A PALINDROME$"
    BUFFER DB 255
DATA ENDS

CODE SEGMENT
START:
    MOV AX, DATA
    MOV DS, AX
    LEA DX, MSG1
    MOV AH, 09H
    INT 21H
    MOV AH, 0AH
    LEA DX, BUFFER
    INT 21H
    XOR CX, CX
    MOV CL, [BUFFER+1]
    DEC CL                
    XOR BX, BX            
    MOV SI,CL            
CHECK_LOOP:
    MOV AL, [BUFFER+2+BX]
    MOV AH, [BUFFER+2+SI] 
    CMP AL, AH            
    JNE NOT_PALINDROME    
    INC BX
    DEC SI
    CMP BX, SI
    JGE PALINDROME        
    JMP CHECK_LOOP

NOT_PALINDROME:
    LEA DX, MSG3
    MOV AH, 09H
    INT 21H
    JMP EXIT

PALINDROME:
    LEA DX, MSG2
    MOV AH, 09H
    INT 21H

EXIT:
    MOV AH, 4CH
    INT 21H

CODE ENDS
END START

